trigger:
- main

pool:
  name: Default

stages:

- stage: Test
  displayName: Python Tests

  jobs:
  - job: PythonTests

    steps:
    - checkout: self

    - script: |
        python3 --version
        pip3 --version
        pip3 install -r backend/reaction-service/requirements.txt
        python3 -m py_compile backend/reaction-service/app.py
      displayName: Run Python Tests